import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

interface ExportData {
  documentName: string;
  summary: string;
  riskScore: number;
  riskFlags: Array<{
    title: string;
    description: string;
    severity: 'high' | 'medium' | 'low';
  }>;
  clauses: Array<{
    title: string;
    description: string;
  }>;
  chatHistory?: Array<{
    role: 'user' | 'assistant';
    content: string;
  }>;
}

export async function exportToPDF(data: ExportData) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = 20;

  // Title
  doc.setFontSize(24);
  doc.setTextColor(88, 28, 135); // Purple color
  doc.text('Legal AI Analysis Report', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 10;

  // Document Name
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(`Document: ${data.documentName}`, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Generated Date
  doc.setFontSize(10);
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, margin, yPosition);
  yPosition += 20;

  // Risk Score Section
  doc.setFontSize(16);
  doc.setTextColor(88, 28, 135);
  doc.text('Risk Analysis', margin, yPosition);
  yPosition += 10;

  doc.setFontSize(14);
  doc.setTextColor(data.riskScore >= 70 ? 220 : data.riskScore >= 40 ? 230 : 180, 
                   data.riskScore >= 70 ? 38 : data.riskScore >= 40 ? 120 : 160, 
                   data.riskScore >= 70 ? 38 : 50);
  doc.text(`Risk Score: ${data.riskScore}/100`, margin, yPosition);
  yPosition += 10;

  // Risk Flags
  if (data.riskFlags.length > 0) {
    doc.setFontSize(12);
    doc.setTextColor(50, 50, 50);
    doc.text('Risk Flags:', margin, yPosition);
    yPosition += 8;

    data.riskFlags.forEach((flag) => {
      // Check if we need a new page
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }

      const severityColor = flag.severity === 'high' ? [220, 38, 38] : 
                             flag.severity === 'medium' ? [230, 120, 50] : [180, 160, 50];
      
      doc.setFillColor(severityColor[0], severityColor[1], severityColor[2]);
      doc.circle(margin + 2, yPosition - 2, 2, 'F');
      
      doc.setFontSize(11);
      doc.setTextColor(50, 50, 50);
      doc.text(flag.title, margin + 8, yPosition);
      
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      const splitDescription = doc.splitTextToSize(flag.description, pageWidth - margin * 2 - 8);
      doc.text(splitDescription, margin + 8, yPosition + 5);
      
      yPosition += 15 + (splitDescription.length - 1) * 4;
    });
  }

  yPosition += 10;

  // Document Summary
  if (yPosition > 220) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setFontSize(16);
  doc.setTextColor(88, 28, 135);
  doc.text('Document Summary', margin, yPosition);
  yPosition += 10;

  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  const splitSummary = doc.splitTextToSize(data.summary, pageWidth - margin * 2);
  doc.text(splitSummary, margin, yPosition);
  yPosition += splitSummary.length * 5 + 15;

  // Key Clauses
  if (data.clauses.length > 0) {
    if (yPosition > 220) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFontSize(16);
    doc.setTextColor(88, 28, 135);
    doc.text('Key Clauses', margin, yPosition);
    yPosition += 10;

    data.clauses.forEach((clause, index) => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }

      doc.setFontSize(12);
      doc.setTextColor(50, 50, 50);
      doc.text(`${index + 1}. ${clause.title}`, margin, yPosition);
      yPosition += 6;

      doc.setFontSize(9);
      doc.setTextColor(80, 80, 80);
      const splitDesc = doc.splitTextToSize(clause.description, pageWidth - margin * 2);
      doc.text(splitDesc, margin, yPosition);
      yPosition += splitDesc.length * 4 + 8;
    });
  }

  // Footer
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Legal AI - Page ${i} of ${totalPages}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  // Save
  doc.save(`LegalAI_Report_${data.documentName.replace(/\.[^/.]+$/, '')}.pdf`);
}

export async function exportElementToPDF(elementId: string, filename: string) {
  const element = document.getElementById(elementId);
  if (!element) {
    console.error('Element not found:', elementId);
    return;
  }

  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
    });

    const imgData = canvas.toDataURL('image/png');
    const doc = new jsPDF('p', 'mm', 'a4');
    
    const imgWidth = 210;
    const pageHeight = 297;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    
    let heightLeft = imgHeight;
    let position = 0;

    doc.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      doc.addPage();
      doc.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    doc.save(filename);
  } catch (error) {
    console.error('Error exporting PDF:', error);
    throw error;
  }
}
